DROP TABLE IF EXISTS TB_USUARIOS;
CREATE TABLE TB_USUARIOS (
     ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY    NOT NULL,
     USERNAME  TEXT    NOT NULL UNIQUE,
     PASSWORD TEXT    NOT NULL
);
-- create
INSERT INTO TB_USUARIOS
    (USERNAME, PASSWORD)
VALUES
    ('xuxadasilva', '$2b$10$8I99eSf.DcubdihXUXO6weT9iriDG0UIm13d5Ji1TCB1kq88LwZdy');

---
DROP TABLE IF EXISTS TB_HEROIS;
CREATE TABLE TB_HEROIS (
     ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY    NOT NULL,
     NOME  TEXT    NOT NULL,
     PODER TEXT    NOT NULL
);
-- create
INSERT INTO TB_HEROIS
    (NOME, PODER)
VALUES
    ('Flash', 'Velocidade'),
    ('Batman', 'Dinheiro'),
    ('Aquaman', 'Marinho');
-- read
SELECT *
FROM TB_HEROIS;
-- update
UPDATE TB_HEROIS 
SET NOME = 'Goku', PODER= 'Deus'
WHERE ID = 1;
--delete
DELETE FROM TB_HEROIS WHERE ID = 2;